@startuml
!include <c4/C4_Context.puml>  

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

'LAYOUT_WITH_LEGEND

title System Context diagram for CETRA

Person(analyst  , Analyst , "<$user> A SOC analyst" )

System(CETRA, "CETRA", "Allows users to input an extension and recieve a verdict")

System_Ext(ext_sys, "External Analyzer", "External analysis such as Virus Total")

Rel(analyst, CETRA, "Uses")
Rel(CETRA, ext_sys, "Request analysis", "API/HTTP")
@enduml